### ISSUE TITLE
Change site license

### ISSUE THREAD

**Issue by nyakase** [PencilVoid/neocities-pencilvoid#9]
Some time ago you emailed me asking if you could switch away from GPLv3. I said you could go ahead, but you haven't changed yet, so I'm concerned you might not have received my reply.

I'm leaving this issue here as a sort of reminder - you can close it if you changed your mind.

<sup>Also, for what it's worth, I'm not convinced my contribution is substantial enough to be blocking a license change like this... But I never really wrapped my head around licensing.</sup>

**Comment by PencilVoid** [comment]
I am actually just really bad at checking my email
